# 主题颜色 是否可切换
theme:
  switch: true  # 为true:页面可切换 false:页面不可切换展示默认
  default: style-light # style-light style-dark

# 网站图标配置
#favicon:
#  logo: favicon-32x32.png
#  icon16: favicon-16x16.png
#  icon32: favicon-32x32.png
#  appleTouchIcon: apple-touch-icon.png
#  webmanifest: /site.webmanifest
#  visibilitychange: true
#  hidden: failure.ico
#  showText: (/≧▽≦/)咦！又好了！
#  hideText: (●—●)喔哟，崩溃啦！

# 用户信息
user:
  name: CC-BLOG
  first_name: BLOG
  last_name: CC-
  email: feng66242@gmail.com
  domain: https://www.imalun.com
  avatar: /img/avatar.jpg
  describe: 个人博客 技术分享。
  ruleText: 暂不接受个人博客以外的友链申请，确保您的网站内容积极向上，文章至少30篇，原创70%以上，部署HTTPS。

# 导航栏
top_bars:
  - title: 主页
    url: /
  - title: 归档
    url: /archives/
    noswup: true
  - title: 分类
    url: /type/

# 侧边栏
sidebar:
  social: # 社交地址
    - name: github
      icon: fab fa-github
      url: https://github.com
    - name: gitee
      icon: iconfont cg-gitee
      url: https://gitee.com
  typedTextPrefix: I`m
  typedText: [ "Web Developer" ]
  info: # 个人信息
    - key: 姓名
      val: CC
    - key: 地址
      val: Shanxi XIAN
    - key: 年龄
      val: 24

# 横幅
banner:
  index:
    type: img
    bgurl: https://pic1.zhimg.com/v2-b3c2c6745b9421a13a3c4706b19223b3_r.jpg?source=1940ef5c
    bannerTitle: 树深时见鹿，<br>溪午不闻钟。
    bannerText: Hi my new friend!

# 页脚
footer:
  powered:
    enable: true
  beian:
    enable: false
    icp:
  copyrightYear:
  live_time:
    enable: false
    prefix: footer.tips
    start_time: 04/10/2022 17:00:00
  custom_text: Hosted by <a href="https://github.com" rel="noopener" target="_blank">Github Pages</a>
